In [13]:
import pandas as pd

In [14]:
# Load the dataset
df = pd.read_csv('cleaned_sms_spam_dataset.csv')
df.head()

  label                                            message
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...

In [15]:
#Encoding the labels
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})
df

      label                                            message
0         0  go until jurong point, crazy.. available only ...
1         0                      ok lar... joking wif u oni...
2         1  free entry in 2 a wkly comp to win fa cup fina...
3         0  u dun say so early hor... u c already then say...
4         0  nah i don't think he goes to usf, he lives aro...
...     ...                                                ...
5164      1  this is the 2nd time we have tried 2 contact u...
5165      0               will ü b going to esplanade fr home?
5166      0  pity, * was in mood for that. so...any other s...
5167      0  the guy did some bitching but i acted like i'd...
5168      0                         rofl. its true to its name

[5169 rows x 2 columns]

In [26]:
df.to_csv('encoded_sms_spam_dataset.csv', index=False)